pipeline:
  identifier: Build_pocrepo_1695291030345
  name: Build pocrepo
  orgIdentifier: default
  projectIdentifier: Sample
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1695291009490
        repoName: deenaboopathy/pocrepo
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
